export const CRON_TIMEZONE = 'UTC';
export const AUDIT_DATA_NUKE_THRESHOLD_DAYS =
  +process.env.AUDIT_DATA_NUKE_THRESHOLD_DAYS!;
export const AUDIT_IP_NUKE_THRESHOLD_DAYS =
  +process.env.AUDIT_IP_NUKE_THRESHOLD_DAYS!;
export const CONTACT_REQUEST_EMAIL_MASK_RETENTION_DAYS =
  +process.env.CONTACT_REQUEST_EMAIL_MASK_RETENTION_DAYS!;
export const CONTACT_REQUEST_RECORD_RETENTION_DAYS =
  +process.env.CONTACT_REQUEST_RECORD_RETENTION_DAYS!;
