name: AWS Elastic Beanstalk Deploy

on:
  workflow_dispatch:

  pull_request:
    # types: [closed]
    # types: [opened, edited, closed]
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install virtualenv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv

      - name: Install and configure Elastic Beanstalk CLI
        run: |
          git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
          python ./aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py
          echo "$HOME/.ebcli-virtual-env/executables" >> $GITHUB_PATH
          eb init 'STO Info Backend (Dev)' --region eu-west-2 --platform Node.js
        env:
          AWS_DEFAULT_REGION: eu-west-2
          AWS_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to AWS Elastic Beanstalk
        run: eb deploy STOInfoBackendDev-env
